import g4f
from newsapi import NewsApiClient
from datetime import datetime, timedelta
import time
from dotenv import load_dotenv
import os

load_dotenv()
API_KEY = os.getenv("API_KEY")
newsapi = NewsApiClient(api_key=API_KEY)

topics = ["маркетинг", "технологии", "реклама", "искусственный интеллект", "социальные сети"]

def filter_advertisements(response_text):
    unwanted_phrases = [
        "Generated by BLACKBOX.AI",
        "try unlimited chat https://www.blackbox.ai"
    ]
    for phrase in unwanted_phrases:
        response_text = response_text.replace(phrase, "")
    return response_text.strip(", \n")

def get_fresh_news():
    week_ago = (datetime.now() - timedelta(days=7)).strftime('%Y-%m-%d')
    news_items = []

    for topic in topics:
        articles = newsapi.get_everything(
            q=topic,
            language='ru',
            from_param=week_ago,
            sort_by='publishedAt',
            page_size=2
        )['articles']

        for article in articles:
            if article['title'] and article['url']:
                news_items.append({
                    "title": article['title'],
                    "description": article['description'] or "Без описания",
                    "date": article['publishedAt'][:10],
                    "source": article['source']['name'],
                    "url": article['url']
                })
    return news_items

def summarize_with_g4f(news_list):
    combined_text = "\n\n".join([
        f"Заголовок: {n['title']}\nОписание: {n['description']}\nДата: {n['date']}\nИсточник: {n['source']}\nСсылка: {n['url']}"
        for n in news_list
    ])

    messages = [
        {
            "role": "system",
            "content": (
                "Ты — ИИ-журналист, который пишет кратко, нейтрально и по делу. "
                "Отформатируй список новостей красиво и структурировано, с эмодзи и нумерацией. "
                "Не выдумывай данные — используй только то, что дано."
            )
        },
        {
            "role": "user",
            "content": f"Сделай краткую и читабельную подборку (5–7 новостей) из текста:\n\n{combined_text}"
        }
    ]

    response = g4f.ChatCompletion.create(
        model="meta-llama/Llama-3.3-70B-Instruct-Turbo",
        provider=g4f.Provider.DeepInfra,
        messages=messages,
        stream=False
    )

    return filter_advertisements(response)

def save_to_file(content):
    filename = "news_report.txt"
    with open(filename, "w", encoding="utf-8") as file:
        file.write(content)
    print(f"\n💾 Результат сохранён в файл: {filename}")

if __name__ == "__main__":
    print("📰 Загружаю реальные новости за последнюю неделю...\n")
    fresh_news = get_fresh_news()

    if not fresh_news:
        print("⚠️ Не удалось получить новости. Проверь API ключ или интернет-соединение.")
    else:
        print("🧠 Обрабатываю новости с помощью g4f...\n")
        summary = summarize_with_g4f(fresh_news)

        print("✨ Подборка актуальных новостей:\n")
        print(summary)

        save_to_file(summary)
        print("\n📅 Конец отчёта.\n")
